baseURL = 'https://chiragdua25.github.io/friction-legal/'
languageCode = 'en-IN'
title = 'Friction Legal'
disableKinds = ['taxonomy', 'term']

[params]
  description = 'Official legal pages for Friction.'
